### PR TITLE
Add restart true to the bespin_web role

### PR DESCRIPTION
**Pull request by johnbradley**
This is to fix an issue where the docker environment was not visible to the starting scripts.
Fixes https://github.com/Duke-GCB/gcb-ansible/issues/48

Ansible docker_container module docs: http://docs.ansible.com/ansible/latest/docker_container_module.html

### CODE REVIEW

**Comment by dleehr** [comment]
So is the issue that the playbook may run with a new environment but unless we mark `restart: true` the in-container process doesn't pick up the new environment?

**Comment by johnbradley** [comment]
I think the core issue is apache is actively running and we are possibly changing files and environment underneath it. The 404 in this case seems to be related to changing out the bespin ui code /srv/ui. There is also an apache warning about the BESPIN_SERVER_NAME environment variable.

**Comment by dleehr** [comment]
> The 404 in this case seems to be related to changing out the bespin ui code /srv/ui.

Ah - the playbook removes the old `/srv/ui` directory (which would be mounted as a volume in an already running container) then creates a new `/srv/ui` directory. The reasoning was to guarantee we didn't have stray files from an old UI release

I think we should update this playbook to clear out the `/srv/ui` directory if it exists, to prevent it from getting disappeared. Ideally we'd not change the contents of that directory if nothing changed.

As for the BESPIN_SERVER_NAME env variable, i'm not sure why that would get lost unless we restart.

**Comment by dleehr** [comment]
I'll merge this since it's been approved and we have other changes to gang together.

**Pull request merged**
