### PR TITLE
Jupyterhub -extended req_runtime from 120 to 240

### PR DESCRIPTION
**Pull request by gsteffen1921**
Peer review requested.

### CODE REVIEW

**Comment by gsteffen1921** [comment]
Sorry about that.   I was actually following your Ipad written steps were we had:
cd roles
git checkout
edit roles
git add
git commit
git push

and had forgotten about the issues tab in Github.

**Comment by dleehr** [comment]
Sure. that's what we did for #37 with PR #51. And that's absolutely the process for submitting a PR and requesting a review, so that was great.

However, one reason we do code reviews through pull requests is for a chance to ask questions before changes get applied into master. Perhaps I didn't make the process clear or explain what it means to branch, pull-request, and merge. In my review of this PR, I chose not to approve it, but instead ask a question. So I was confused why you merged it without addressing my question.

I recognize this process is new and complicated. Thanks for pressing forward!

**Comment by dleehr** [comment]
On re-reading my comment, I certainly should have been more clear. This is a process that @johnbradley and I do every day, so I forget that not everyone has the same context/experience with pull requests.

**Comment by gsteffen1921** [comment]
Would this be a good opportunity (for exposure/experience) to go through the process of restoring the branch, reverting back and doing what was originally requested in issues #106?

**Comment by dleehr** [comment]
> Would this be a good opportunity (for exposure/experience) to go through the process of restoring the branch, reverting back and doing what was originally requested in issues #106?

Absolutely. 👍

**Pull request merged**
